print("Evaluación N°1 CCNA DEVNET")
nombre = input("Por favor, ingresa tu nombre: ")
apellido = input("Por favor, ingresa tu apellido: ")
seccion = input("Por favor, ingresa tu sección: ")
sede = input("Por favor, ingresa tu sede: ")

print("Los datos ingresados son:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Sección:", seccion)
print("Sede:", sede)